### ISSUE TITLE
picovoice failure

### ISSUE THREAD

**Issue by peterkurpis** [DevMiser/Lumina#9]
Hello.  I've set up my new Raspberry Pi 4 twice, with two different SD cards (8 GB, 32 GB both new), and two different sizes of OS (regular and full size, legacy 64-bit).  I get the same error on both, on the first try:

pi@raspberrypi:~/Lumina $ python3 Lumina.py
Traceback (most recent call last):
  File "/home/pi/Lumina/Lumina.py", line 411, in <module>
    o = create(
  File "/home/pi/.local/lib/python3.9/site-packages/pvleopard/_factory.py", line 44, in create
    return Leopard(
  File "/home/pi/.local/lib/python3.9/site-packages/pvleopard/_leopard.py", line 202, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status](
pvleopard._leopard.LeopardActivationRefusedError: Initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `0000012C`)
pi@raspberrypi:~/Lumina $

Any ideas?  (I was once a pretty good C programmer, but had a stroke a few years ago.  I say this, because it could be something not so bright.)  This is a pretty magic project, by the way, so many thanks!

**Comment by peterkurpis** [comment]
I went to picovoice's website, and they have apparently deleted my account, for no known reason.  I have followed up, but am worried they won't respond.  Waiting...

**Comment by peterkurpis** [comment]
Hello, DevMiser.  You can close this.  Unfortunately, I have not been able to get through to picovoice.ai -- not to support, not to Alireza, ...  
Since I can't get the passkey, I will give up.  If you have a version with another voice service, or a version where I can type in the request, let me know.  Otherwise, please close.  Thanks!
